.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.\" $Id: wmbiff.1,v 1.2 2001/06/19 03:38:58 dwonis Exp $
.\"
.\" wmbiff.1 and wmbiffrc.5 are copyright 1999-2001 by
.\" Jordi Mallach <jordi@debian.org>
.\"
.\" This is free documentation, see the latest version of the GNU
.\" General Public License for copying conditions. There is NO warranty.
.TH WMBIFF 1 "March 12, 2001" "wmbiff"

.SH NAME
WMBiff \- A dockable Mailbox Monitor

.SH SYNOPSIS
.B wmbiff
[-display <display name>] [-geometry +XPOS+YPOS] [-c <filename>] [-h] [-v]
.br

.SH DESCRIPTION
WMbiff displays the status of up to five mailboxes. It gives information
about new mail, if any, or total number of messages. It also has mail
retrieval capabilies, and can be configured to do this automatically. At the
moment, UNIX-style, POP3 and IMAP4 mailboxes are supported. WMbiff also
supports Licq history files, displaying the number of new messages in your
running Licq session, as if they were mail.

The mailboxes are displayed in 5 different lines, each one with its own
description of up to five chars. If no mail is present in a given mailbox,
WMbiff will display the total number of mails in cyan. If there's new mail
in the box, the number of new messages will be displayed in yellow. When new
mail arrives, this number will optionally flash for a small period of time,
and also optionally, a command can be executed on mail arrival (for example,
opening your mail reader or playing a sound file).

Pressing mouse button 1 will execute a command, defined in the user's config
file. Mouse button 3 will execute a command to fetch mail, if defined.
.PP

.SH OPTIONS
.TP
.B \-h
Show summary of options.
.TP
.B \-v
Show version of program.
.TP
.B \-display <display name>
Use an alternate X Display.
.TP
.B \-geometry <geometry>
Initial window position.
.TP
.B \-c <filename>
Use specified config file.

.SH BUGS
Please send any bug reports or suggestions to Gennady Belyakov
<gb@ccat.elect.ru>.
.br

.SH FILES
.TP
.I ~/.wmbiffrc
peruser wmbiff configuration file.

.SH AUTHOR
This manual page was written by Jordi Mallach <jordi@sindominio.net>,
originally for the Debian GNU/Linux system (but may be used by others).

.SH SEE ALSO
.PD 0
.TP
\fBwmbiffrc\fP(5)
.PP
\fI/usr/share/doc/wmbiff/examples/sample.wmbiffrc\fP
(or equivalent for your system)
